#! /bin/bash

# Provision a vagrant instance.

set -e

# Remove some vagrant cruft
rm -f /home/vagrant/postinstall.sh

# Add some repositories and update the repo
apt-get update -y
apt-get install -y python-software-properties
apt-get update -y

# Install packages
apt-get install -y    \
  curl                \
  dstat               \
  iftop               \
  iotop               \
  iperf               \
  lsof                \
  man-db              \
  mlocate             \
  rsync               \
  sysstat             \
  wget

# Enables sudo'd commands to take advantage of forwarded keys.
echo 'Defaults env_keep += "SSH_AUTH_SOCK"' > /etc/sudoers.d/ssh-auth-sock
chmod 0440 /etc/sudoers.d/ssh-auth-sock

ln -s /vagrant /home/vagrant/csc110

# Color prompts, please.  What am I, a farmer?
sed -i 's|#force_color|force_color|' ~vagrant/.bashrc
